CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Bets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CreatorId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ClosedAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Bets" PRIMARY KEY ("Id")
);

CREATE TABLE "Outcomes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "BetId" integer NOT NULL,
    "Votes" integer NOT NULL,
    CONSTRAINT "PK_Outcomes" PRIMARY KEY ("Id")
);

CREATE TABLE "UserBets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BetId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OutcomeId" integer NOT NULL,
    CONSTRAINT "PK_UserBets" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "RegistrationDate" timestamp with time zone NOT NULL,
    "NumberOfWins" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230430153339_InitialCreate', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Outcomes" ADD "Selections" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230501093251_OutcomeMigration', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bets" ADD "WinOutcomeId" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230501121623_BetWinOutcomeIdMigr', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserBets" ADD "HasVoted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230501192124_UserBetVotedStatusMig', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ADD "Role" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230502103142_UserRoleMig', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Bets" DROP COLUMN "ClosedAt";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230510203357_RemoveClosedAt', '7.0.5');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230510230525_RemoveVotingStage', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "UserBets" ALTER COLUMN "UserId" TYPE bigint;

ALTER TABLE "UserBets" ALTER COLUMN "OutcomeId" TYPE bigint;

ALTER TABLE "UserBets" ALTER COLUMN "BetId" TYPE bigint;

ALTER TABLE "UserBets" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "Outcomes" ALTER COLUMN "BetId" TYPE bigint;

ALTER TABLE "Outcomes" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "Bets" ALTER COLUMN "WinOutcomeId" TYPE bigint;

ALTER TABLE "Bets" ALTER COLUMN "CreatorId" TYPE bigint;

ALTER TABLE "Bets" ALTER COLUMN "Id" TYPE bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230510234451_IdLong', '7.0.5');

COMMIT;

