version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: DrTau
      POSTGRES_PASSWORD: MyPassword
      POSTGRES_DB: betmeDb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=betmeDb;Username=DrTau;Password=MyPassword
    ports:
      - "5091:5091"
    depends_on:
      - db

volumes:
  db-data:
